apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Microservices-Extra-Kube-Manifests/HTTProute.yaml
  - Microservices-Extra-Kube-Manifests/target-grp.yaml

helmCharts:
  - name: onlineboutique
    repo: oci://ghcr.io/judecodehub
    version: 0.10.4
    releaseName: mj-boutique-app
    namespace: mj-boutique-app
    valuesFile: Helm-Chart/values.yaml
