

images:
  adservice:
    repository: ghcr.io/judecodehub/microservices-demo/adservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  cartservice:
    repository: ghcr.io/judecodehub/microservices-demo/cartservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  checkoutservice:
    repository: ghcr.io/judecodehub/microservices-demo/checkoutservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  currencyservice:
    repository: ghcr.io/judecodehub/microservices-demo/currencyservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  emailservice:
    repository: ghcr.io/judecodehub/microservices-demo/emailservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  frontend:
    repository: ghcr.io/judecodehub/microservices-demo/frontend
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  loadgenerator:
    repository: ghcr.io/judecodehub/microservices-demo/loadgenerator
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  paymentservice:
    repository: ghcr.io/judecodehub/microservices-demo/paymentservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  productcatalogservice:
    repository: ghcr.io/judecodehub/microservices-demo/productcatalogservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  recommendationservice:
    repository: ghcr.io/judecodehub/microservices-demo/recommendationservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c
  shippingservice:
    repository: ghcr.io/judecodehub/microservices-demo/shippingservice
    tag: sha-49305edd95d1b1a1493c44054423b7523880497c

serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

networkPolicies:
  create: false

sidecars:
  create: false

authorizationPolicies:
  create: false

opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: "PROJECT_ID"

googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false

seccompProfile:
  enable: false
  type: RuntimeDefault

securityContext:
  enable: true

adService:
  create: true
  name: adservice
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

cartService:
  create: true
  name: cartservice
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

checkoutService:
  create: true
  name: checkoutservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

currencyService:
  create: true
  name: currencyservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

emailService:
  create: true
  name: emailservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

frontend:
  create: true
  name: frontend
  externalService: false
  cymbalBranding: false
  platform: aws
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
    - "*"
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

paymentService:
  create: true
  name: paymentservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

productCatalogService:
  create: true
  name: productcatalogservice
  extraLatency: ""
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

recommendationService:
  create: true
  name: recommendationservice
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi

shippingService:
  create: true
  name: shippingservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""

shoppingAssistantService:
  create: false
  name: shoppingassistantservice
