name: Microservices Trigger CI

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.changed.outputs.services }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed services
        id: changed
        env:
          EVENT_NAME: ${{ github.event_name }}
          BEFORE_SHA: ${{ github.event.before }}
          CURRENT_SHA: ${{ github.sha }}
        run: |
          if [ "$EVENT_NAME" = "workflow_dispatch" ] || [ -z "$BEFORE_SHA" ] || [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            CANDIDATES=$(ls -d src/*/ | cut -d'/' -f2)
          else
            CANDIDATES=$(git diff --name-only "$BEFORE_SHA" "$CURRENT_SHA" | grep '^src/' | cut -d'/' -f2 | sort -u)
          fi

          SERVICES=$(for s in $CANDIDATES; do [ -d "src/$s" ] && echo "$s"; done | jq -R -s -c 'split("\n")[:-1]')

          echo "Detected services: $SERVICES"
          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"


  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    uses: ./.github/workflows/microservice-ci.yaml

    with:
      service: ${{ matrix.service }}
